### ISSUE TITLE
random deploy failures

### ISSUE THREAD

**Issue by jamespeerless** [linemanjs/rails-lineman#11]
1) Not sure what's going on but I am using capistrano for my deploys and during asset compilation every few deploys it will randomly fail with this message:

rake aborted!

```
    rails-lineman failed when trying to run `lineman build`.

    Attempted to execute `lineman` as if on your PATH, then directly from
    the npm binstub at `./node_modules/.bin/lineman`.

    Try again after installing lineman globally with `npm install -g lineman`
```

/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/lineman_doer.rb:102:in `run_lineman_build'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/lineman_doer.rb:40:in`block in perform_lineman_build'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/lineman_doer.rb:63:in `chdir'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/lineman_doer.rb:37:in`perform_lineman_build'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/lineman_doer.rb:17:in `precompile_assets'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/meta_lineman_doer.rb:10:in`map'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/rails_lineman/meta_lineman_doer.rb:10:in `precompile_assets'
/home/deploy/example.com/shared/bundle/ruby/2.1.0/gems/rails-lineman-0.3.0/lib/tasks/assets_precompile.rake:12:in`block (2 levels) in <top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

If I ssh into the machine as the deploy user I can access lineman executable (it was installed globally as the message suggests) and the fact that it will then work the next time I run it is confusing.  Sporadically this fails.

2) Another question I have is during the npm install phase of deployment I see it fetching a million packages and they show up in red in my terminal (as if they're failing) even though it works:

DEBUG[f293cd84]     GET
DEBUG[f293cd84]      https://registry.npmjs.org/testem/0.6.15
DEBUG[f293cd84]     npm

Is there any way to set this up so I don't have to fetch and install all packages on every deploy?

**Comment by searls** [comment]
Hey James,

1) I've never seen the error you're describing above, but after reading point (2), it's probably what you'd experience if npm install was failing. Probably best to figure that out first

2) I think some approach that caches the npm modules is the best one, and I don't have a great answer for that. A PR in this regard would be quite welcome! Two short-term ideas to improve that:
- You could, of course, commit your `node_modules` directory and push it up (which would dramatically decrease install time)
- You could install lineman globally to your build server `npm i -g lineman` and then remove lineman from your package.json such that the npm install only included whatever other deps you needed.
