### ISSUE TITLE
deploy issues

### ISSUE THREAD

**Issue by justinbkay** [linemanjs/rails-lineman#8]
If I try to run the rails app in development it tells me that it can't find the app.css or the app.js files:

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/stylesheets/lineman/app.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/javascripts/lineman/app.js

Which is because there is no routes for these files:

ActionController::RoutingError (No route matches [GET] "/assets/lineman/app.css"):
## Gemfile looks like this:

source 'https://rubygems.org'
gem 'rails', '4.1.1'
gem 'mysql2'
gem 'spring',    group: :development
gem 'uglifier', '>= 1.3.0'
gem 'bcrypt', '~> 3.1.7'
gem 'unicorn'
gem 'capistrano-rails', group: :development
gem 'pry'
gem 'active_model_serializers'
gem 'rails-lineman'
gem 'prawn'

**Comment by searls** [comment]
In development you need to work off the lineman app [http://localhost:8000](http://localhost:8000). It will provide the missing routes b/c it's actively serving them. It'll proxy everything else back to the rails backend

**Comment by justinbkay** [comment]
Yes, that works fine, I was just trying to test what production would look like.  It seems to me that it has to do with fingerprinting of the files.  The rails link is not pointing to the fingerprinted filename, app-bba9e00ce69ddb0165d83560fe581879.js, but to the regular app.js.  I'm not super strong with the asset pipeline, so it may just be some configuration problem in rails.

**Comment by searls** [comment]
Production deploys require you to run rake assets:precompile

**Comment by justinbkay** [comment]
Yes, the assets are compiled and in the correct directory, it's just the link isn't pointing to the fingerprinted file.

**Comment by searls** [comment]
Oh that's surprising. Are you running the app in production mode? Have you configured production.rb to serve static assets?

**Comment by justinbkay** [comment]
Seems to work in a live production environment,  I did end up adding gem 'sprockets-rails', :require => 'sprockets/railtie' to my gemfile to get the assets:precompile to work without errors though.

**Comment by searls** [comment]
Really? Without that require it failed? Had you perhaps removed the sprockets require at some point from application.rb?

**Comment by justinbkay** [comment]
No, I just never included the asset pipeline when I created the app.

rails new server -d mysql -J -T -S

Done, without errors.
rake aborted!
Don't know how to build task 'assets:precompile:original'
/Users/jkay/.rvm/gems/ruby-2.0.0-p353/gems/rails-lineman-0.2.0/lib/tasks/assets_precompile.rake:11:in `block (2 levels) in <top (required)>'
/Users/jkay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in`load'
/Users/jkay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `block in load'
/Users/jkay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in`load_dependency'
/Users/jkay/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
-e:1:in`<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

**Comment by searls** [comment]
Ah well yeah that would do it.

**Comment by justinbkay** [comment]
So, after getting this to work in a production environment, I now can't use it in development.

The rails links for css and js don't match the ones for lineman.

rails wants /assets/lineman/app.js
and /assets/lineman/app.css

<% content_for :lineman do %>
    <%= stylesheet_link_tag "lineman/app" %>
    <%= javascript_include_tag "lineman/app" %>
<% end %>

lineman is mapped to /javascripts/lineman/app.js and /stylesheets/lineman/app.css

If I configure the mapping for js and css to /assets/lineman, only one gets mapped (the second mapping) and the other one is not found (over written?).  I have no idea why this was working before and not now.  Except that the rails side has fingerprinted the filenames now.

**Comment by searls** [comment]
I'm abundantly confused at this point as to what your setup is.

**Comment by searls** [comment]
I think to carry this forward I'll need a sample repo or something

**Comment by srt32** [comment]
I'm seeing the same issue where I was able to load up the app in development, then precompiled assets for production and deployed (it worked on production), but now get `ActionController::RoutingError (No route matches [GET] "/assets/lineman/app.js"):` on development.

Here's a toy app showing the issue: https://github.com/srt32/talk-client-two.  The diff of interest is https://github.com/srt32/talk-client-two/compare/b818af60030214f6c342eac89cb6343a96bf7031...8fb91f64c272b59906743f421daae17a1aa864c1.  There is quite a bit of noise as I was experimenting with some things but it sounds like I have the same fingerprinting problem mentioned above.

Thanks for any debugging help!

EDIT: To fix it I ran `rm -rf public/assets/*` from the server directory.  Seems like a pain to have to clear out the precompiled assets but that did it.

**Comment by searls** [comment]
Yeah, so it seems like if `public/assets` exist locally, then Rails 4 will not serve up `/javascripts/` and `/stylesheets/`. I honestly don't know the best way to work around this.

One idea is that lineman-rails could set up the static routes it is already setting up in addition to several more, all named "assets" and pointing to each of js/css/webfonts/img. That worries me somewhat, though, because it could set people up to refer to a path that will only work in development.
